config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  patch "profiles/:id/scan", to: "profiles#scan"
  root "application#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
require 'singleton'

class Client
  include Singleton
  
  def bitly_client
    @client = Bitly::API::Client.new(token: ENV["bitly_token"])
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  include PgSearch::Model

  validates :profile_name, presence: true
  validates :github_username, uniqueness: true

  validates :github_profile_image,
            format: {
              with: %r(avatars[0-9]+.githubusercontent.com\/u\/\w+)
            },
            uniqueness: true

  validates :github_address,
            format: {
              with: %r(github\.com\/[\w]+[-\w]*)
            },
            uniqueness: true

  pg_search_scope :search_by_term, against: [:profile_name, :github_username, :organization, :location],
                    using: {
                      tsearch: {
                        any_word: true,
                        prefix: true
                      }
                    }

  def self.search(query)
    if query.nil? or query.empty?
      @profiles = Profile.all
    else
      @profiles = Profile.search_by_term(query)
    end
  end

end

app/models/profile_spider.rb
require 'nokogiri'
require 'open-uri'

class ProfileSpider

  def scrape(url, profile_name)
    profile_params = {}
    source_code = Nokogiri::HTML(URI.open(url))
    container = source_code.xpath("//div[@class='h-card mt-4 mt-md-n5']")

    github_username = github_username(container)

    profile_params = {
      profile_name: profile_name,
      github_address: url,
      github_username: github_username,
      github_profile_image: github_profile_image(container),
      shorten_url: github_shorten_url(url),
      organization: organization(container),
      location: location(container),
      amount_of_followers: amount_of_followers(container, github_username),
      amount_of_following: amount_of_following(container, github_username),
      amount_stars: amount_stars(container, github_username),
      amount_contributions: amount_contributions(source_code)
    }

    profile_params
  end

  private
  
  def github_username(container)
    container.css(
      "span[@class='p-nickname vcard-username d-block']"
    )&.text&.squish
  end

  def github_profile_image(container)
    github_profile_url = container.css(
      "img[@class='avatar avatar-user width-full border bg-white']"
    ).attr('src').text&.squish
  end

  def github_shorten_url(url)
    Client.instance.bitly_client.shorten(long_url: url).link
  end

  def organization(container)
    container.css(
      "a[@class='user-mention']"
    )&.text&.squish
  end

  def location(container)
    container.css("span[@class='p-label']")&.text&.squish
  end

  def amount_of_followers(container, github_username)
    followers = container.css(
      "a[@href='/#{github_username}?tab=followers']"
    )
    followers.css(
      "span[@class='text-bold text-gray-dark']"
    )&.text&.squish.to_i
  end
    
  def amount_of_following(container, github_username)
    following = container.css(
      "a[@href='/#{github_username}?tab=following']"
    )
    following.css(
      "span[@class='text-bold text-gray-dark']"
    )&.text&.squish.to_i
  end

  def amount_stars(container, github_username)
    stars = container.css(
      "a[@href='/#{github_username}?tab=stars']"
    )
    stars.css(
      "span[@class='text-bold text-gray-dark']"
    )&.text&.squish.to_i
  end

  def amount_contributions(container)
    amount_of_contributions = container.xpath(
      "//div[@class='js-yearly-contributions']"
    ).css(
      "h2[@class='f4 text-normal mb-2']"
    )&.text&.squish
    amount_of_contributions.scan(/\d+/).first.to_i
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
    @profiles = Profile.none
    render 'layouts/home'
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.search(params[:search])
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    params = scrape(profile_params)
    @profile = Profile.new(params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    params = scrape(profile_params)
    respond_to do |format|
      if @profile.update(params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def scan
    if set_profile
      profile_params = scrape({ github_address: @profile.github_address, profile_name: @profile.profile_name })
      if @profile.update(profile_params)
        redirect_to action: 'show', notice: 'Profile was successfully updated.'
      else
        redirect_to action: 'show', notice: 'An error occuried trying to rescan profile values.'
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(
        :profile_name,
        :github_address,
        :github_username,
        :amount_of_followers,
        :amount_of_following,
        :amount_stars,
        :amount_contributions,
        :github_profile_image,
        :organization,
        :location,
        :search
      )
    end

    def scrape(params)
      spider = ProfileSpider.new
      response = spider.scrape(params[:github_address], params[:profile_name])
    rescue => e
      puts("Error: #{e}")
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= image_tag("logo-white.png", { width: "30", height: "30", class: "d-inline-block align-top", style: "margin-right  : 1em;" }) %>
      <a class="navbar-brand" href="/">IndexerHub</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
        <div class="navbar-nav justify-content-end">
          <a class="nav-item nav-link" href="<%= new_profile_path %>">Register profile</a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/home.html.erb
<%= render partial: 'partials/search', locals: { width: "15%", height: "15%" } %>

app/views/partials/_search.html.erb
<body>
  <%= image_tag("logo.png", { width: width, height: height, class: "block item-centralize", style: "margin-top: 3em;" }) %>
  <%= image_tag("title.png", { width: width, height: height, class: "block item-centralize" }) %>
  <%= form_tag(profiles_path, method: :get) do %>
    <div class="search-container">
      <div class="input-group">
        <div class="input-group-append item-centralize">
          <%= text_field_tag(:search, params[:search], { class: "form-control py-2", style: "width: 30em;"}) %>
          <span>
            <%= submit_tag("Search", { class: "btn btn-outline-secondary" }) %>
          </span>
        </div>
      </div>
      <% if @profiles.present? %>
        <%= label_tag(@profiles.count.to_s + " profiles found", nil, class: "label-centered text-muted" ) %>
      <% end %>
    </div>
  <% end %>
  <%= yield %>
</body>
<style>
  .search-container {
    margin-top: 3em;
    margin-bottom: 3em;
  }
  .item-centralize {
    margin: 0 auto;
  }
  .block {
    display: block;
  }
  .label-centered {
    margin-top: 1em;
    margin-left: 41em;
  }
</style>

app/views/partials/_userprofile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  </head>
  <body>
    <div class="card" style="width: 13rem;">
      <% if profile.github_profile_image %>
        <img class="card-img-top" src="<%= profile.github_profile_image %>" alt="User image">
      <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= profile.profile_name %></h5>
        <h6 class="card-text"><%= profile.shorten_url %></h6>
        <div class="card_body btn-group", style="margin: 0 auto;">
          <td><%= button_to('Show', profile, { class: "btn btn-outline-success mr-3", method: :get } ) %></td>
          <td><%= button_to('Edit', edit_profile_path(profile), { class: "btn btn-outline-secondary", method: :get }) %></td>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
  <style>
  </style>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
    <div class="card" style="margin-left: 25em; margin-right: 25em; margin-top: 5em;">
      <h4 class="d-flex justify-content-center", style="margin-top: 1em;"><b><%= title %></b></h4>
      <% if profile.errors.any? %>
      <div class="d-flex justify-content-center" id="error_explanation">
        <div style="margin-top: 1em; color: red;">
          <h5><b><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</b></h2>
          <ul>
            <% profile.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="form-group" style="margin: 2em;">
      <%= form.label :profile_name %>
      <%= form.text_field :profile_name, {class: "form-control"} %>
    </div>

    <div class="form-group", style="margin-left: 2em; margin-right: 2em;">
      <%= form.label :github_address %>
      <%= form.text_field :github_address, {class: "form-control"} %>
    </div>

    <%# <div class="btn-group" style="margin: 0 auto; margin-bottom: 1.5em;"> %>
      <div class="card-body btn-group">
      <%= form.submit button[0], { class: "mt-auto btn btn-outline-success mr-5 rounded-lg" } %>
      <%= link_to button[1], profiles_path(@profile), { class: "mt-auto btn btn-outline-danger rounded-lg"} %>
      </div>
    <%# </div> %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<%= render 'form', {profile: @profile, title: 'Editing Profile', button: ['Update', 'Back']} %>

app/views/profiles/index.html.erb
<p id="flash"><%= notice %></p>

<%= render partial: 'partials/search', locals: { width: "10%", height: "10%" } %>

<body>
  <div class="list-group grid-container">
    <% @profiles.each do |profile| %>
      <div class="grid-item">
        <%= render partial: 'partials/userprofile', locals: { profile: profile } %>
      </div>
    <% end %>
  </div>
</body>

<style>
  .grid-container {
    display: grid;
    grid-template-columns: auto auto auto auto auto;
    padding: 1em;
    align-items: start;
  }
  .grid-item {
    padding: 5%;
    font-size: 20px;
    text-align: center;
  }
</style>

app/views/profiles/new.html.erb
<%= render 'form', { profile: @profile, title: 'Register profile', button: ['Register', 'Back'] } %>

app/views/profiles/show.html.erb
<div class="card" style="width: 25rem; margin: 0 auto;">
  <img class="card-img-top rounded-circle" src="<%= @profile.github_profile_image %>" alt="User image" style="width: 50%; margin: 0 auto; margin-top: 2em;">
  <div class="card-body">
    <h5 class="card-title" style="text-align: center;"><%= @profile.profile_name %></h5>
    <p class="card-text" style="text-align: center;"><%= @profile.github_username %></p>
  </div>
  <ul class="list-group">
    <li class="list-group-item"><b><%= @profile.amount_of_followers %></b> followers</li>
    <li class="list-group-item"><b><%= @profile.amount_of_following %></b> following</li>
    <li class="list-group-item"><b><%= @profile.amount_stars %></b> stars</li>
    <li class="list-group-item"><b><%= @profile.amount_contributions %></b> contributions</li>
    <% if @profile.organization.present? %>
      <li class="list-group-item"><%= @profile.organization %></li>
    <% end %>
    <% if @profile.location.present? %>
    <li class="list-group-item"> <%= @profile.location %> </li>
    <% end %>
    <li class="list-group-item"><a href="<%= @profile.github_address %>" target="_blank"> <%= @profile.github_address %> </a></li>
  </ul>
  <div class="card-body btn-group" style="margin: 0 auto;">
    <%= button_to('Rescan', { action: 'scan', profile_id: @profile }, method: :patch, class: "btn btn-outline-success mr-3" ) %>
    <%= button_to('Edit', edit_profile_path(@profile), { class: "btn btn-outline-secondary mr-3", method: :get } ) %>
    <%= button_to('Destroy', @profile, { class: "btn btn-outline-danger mr-3", method: :delete, data: { confirm: 'Are you sure?' } } ) %>
    <%= button_to('Back', profiles_path(@profile), { class: "btn btn-outline-danger", method: :get } ) %>
  </div>
</div>